{% set name = "openexr" %}
{% set version = "3.1.5" %}
{% set sha256 = "93925805c1fc4f8162b35f0ae109c4a75344e6decae5a240afdfce25f8a433ec" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AcademySoftwareFoundation/openexr/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=openexr
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - imath {{ version }}
    - zlib

test:
  commands:
    - test -e $PREFIX/include/OpenEXR/OpenEXRConfig.h  # [unix]
    - test -e $PREFIX/include/OpenEXR/IexConfig.h      # [unix]
    - test -e $PREFIX/lib/libIex$SHLIB_EXT             # [unix]
    - test -e $PREFIX/lib/libIlmThread$SHLIB_EXT       # [unix]
    - test -e $PREFIX/lib/libImath$SHLIB_EXT           # [unix]
    - test -e $PREFIX/lib/libOpenEXR$SHLIB_EXT         # [unix]

about:
  home: https://github.com/openexr/openexr
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: |
    OpenEXR is a high dynamic-range (HDR) image file format developed by
    Industrial Light & Magic for use in computer imaging applications.
  description: |
    OpenEXR is a high dynamic-range (HDR) image file format developed by
    Industrial Light & Magic (ILM) for use in computer imaging applications. It
    supports stereoscopic and deep images. Weta Digital, Walt Disney Animation
    Studios, Sony Pictures Imageworks, Pixar Animation Studios, DreamWorks, and
    other studios, companies, and individuals have made contributions to the
    code base. The file format has seen wide adoption in a number of industries.
  doc_url: http://www.openexr.com/documentation.html
  dev_url: https://github.com/openexr/openexr

extra:
  recipe-maintainers:
    - aaronang
    - SylvainCorlay
    - wolfv
    - npavlovikj
    - JohanMabille
    - pkgw
